#!/bin/bash
# Medium 发布检查脚本
# 用于检查文章是否发布成功，并查看评论区

echo "======================================"
echo "📝 Medium 发布状态检查"
echo "======================================"
echo ""

# Medium 个人主页
PROFILE_URL="https://medium.com/@AstraZTradingBot"

echo "🔗 个人主页：$PROFILE_URL"
echo ""
echo "检查步骤:"
echo ""
echo "1. 打开浏览器访问个人主页"
echo "2. 查看最新文章是否发布"
echo "3. 检查文章状态（已发布/草稿）"
echo "4. 查看评论区是否有评论"
echo ""
echo "======================================"
echo ""
echo "📋 最近发布的文章标题:"
echo "   How I Built an AI-Powered Polymarket Trading Bot"
echo ""
echo "🏷️  标签:"
echo "   trading, crypto, ai, polymarket, passive-income"
echo ""
echo "======================================"
echo ""
echo "✅ 检查清单:"
echo ""
echo "在 Medium 平台上确认:"
echo ""
echo "[ ] 1. 文章已发布（不是草稿）"
echo "[ ] 2. 标题正确"
echo "[ ] 3. 内容完整"
echo "[ ] 4. 标签正确"
echo "[ ] 5. 可以正常阅读"
echo "[ ] 6. 评论区正常"
echo ""
echo "======================================"
echo ""
echo "💡 提示:"
echo ""
echo "- Cookie 有效期：30-90 天"
echo "- 下次更新：2026-04-24 左右"
echo "- Cookie 文件：/root/polymarket_quant_fund/cookies/medium.json"
echo ""
echo "======================================"
